### ISSUE TITLE
Error Scan QR 

### ISSUE THREAD

**Issue by cerfox** [Dvnz99/wabot#3]
Ketika Di Scan QR, Bot tidak mau ter login / tidak mau connect, sampai refresh qr beberapa kali tetap sama.

**Comment by Dvnz99** [comment]
yg diubah text.js sama handler sj, yg lain gausah

**Comment by Dvnz99** [comment]
biar gk error, soalnya aman2 aja gw pake

**Comment by cerfox** [comment]
permisi gan, untuk code selain config saya ga ada yg ubah kok, itupun di config cuma masukin api key saja,
yg saya maksud error nya untuk scan qr baruagan bisa coba scan qr baru nanti pasti problemnya sama, mungkin solusinya ada di : https://github.com/adiwajshing/Baileys/issues/782 tapi saya masih bingung buat nerapinnya gimana, mungkin agan @Dvnz99 bisa bantu, terimakasih :D

**Comment by Mr7Gabriel** [comment]
> permisi gan, untuk code selain config saya ga ada yg ubah kok, itupun di config cuma masukin api key saja, yg saya maksud error nya untuk scan qr baru, agan bisa coba scan qr baru nanti pasti problemnya sama, mungkin solusinya ada di : [adiwajshing/Baileys#782](https://github.com/adiwajshing/Baileys/issues/782) tapi saya masih bingung buat nerapinnya gimana, mungkin agan @Dvnz99 bisa bantu, terimakasih :D

Untuk Soal ini dapat diubah ke Versi Lebih Tinggi yang terletak di: ./node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js dan edit isinya dan cari this.version = [X, XXXX, XX]; ubah dengan
"2, 2142, 12" atau lebih tinggi

Catatan: Ada kemungkinan terjadi kesalahan lain jika diganti

**Comment by Mr7Gabriel** [comment]
Masih ada yang mau ditanyakan?

**Comment by cerfox** [comment]
> Masih ada yang mau ditanyakan?

iya bang, yg jadi problem ketika saya deploy di repl.it itu node_modules gabisa di akses / di edit file nya, aku dah coba di pc jalan.

**Comment by Mr7Gabriel** [comment]
> > Masih ada yang mau ditanyakan?
> 
> iya bang, yg jadi problem ketika saya deploy di repl.it itu node_modules gabisa di akses / di edit file nya, aku dah coba di pc jalan.

Upload aja  kalau emang gak bisa, biar jalan di Repl.it
